# Generated by Django 5.1.6 on 2025-02-22 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_listings', to='users.companyprofile'),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='auction_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.auctionlisting'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='users.buyerprofile'),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_listings', to='core.category'),
        ),
        migrations.AddField(
            model_name='comment',
            name='auction_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.auctionlisting'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.buyerprofile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.buyerprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='auction_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.auctionlisting'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.buyerprofile'),
        ),
        migrations.AddField(
            model_name='picture',
            name='auction_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='core.auctionlisting'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auction_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to='core.auctionlisting'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='users.buyerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'auction_listing')},
        ),
    ]
