# Generated by Django 5.1.6 on 2025-02-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auctionlisting_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_outbid_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
